# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-12 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Swiped',
            new_name='Swipre',
        ),
    ]
