# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-13 01:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20181212_1759'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Swipre',
            new_name='Swiped',
        ),
    ]
